### PR TITLE
Ability to determine whether or not the click should be granted.

### PR DESCRIPTION
**Pull request by tylerjroach**
I realize this will force a change for everyone for the onTabSelectedListener by having to specify the return type, however, this method does have it's advantages. Feel free to reject or propose an alternate solution.

I had to make this change for a project I'm working on because some of the app isn't functional before a successful login. We still wanted to show new users what the app has to offer, however, when a user clicks on a tab that requires login, I then throw up a Sign-In/Sign-Up DialogFragment. Because the user was not actually redirected to the selected tab, I did not want to update the navigation bar. By returning false in onTabSelected, it prevents the tab selection from occurring.

### CODE REVIEW

**Comment by tylerjroach** [comment]
Also fixed method typo
setNotificationMarginLef -> setNotificationMarginLeft

**Comment by aurelhubert** [comment]
@tylerjroach Thanks for your interest and time!

For the first commit, I think it's an interesting point. I'm still not sure about the best UX implementation. Maybe you should display a screen with an explanation (which doesn't required to update the listener). The user sees why the screen is "locked" and if you add a button, he could access directly to the login part. On the other hand, your solution is interesting because it allows developers to create customized behaviors. What do you think is the best?

For the second commit, good catch, I have lost the "t" somewhere... :)

**Comment by tylerjroach** [comment]
Yeah I realize my need may be a little more custom than most. I have a login dialog fragment that pops up  rather than a full screen fragment. It's what works best for us from a UI standpoint, but feel free to ignore that as I'm not to sure it's necessary for others. I may also work on a pull request to allow custom view CoordinatorLayout behaviors, not just the FAB and snackbar.

**Comment by aurelhubert** [comment]
The only problem is that it breaks the current interface, but your idea is good and we could maybe add the changes in the next major update.

Thanks again for your work.

**Comment by mgursch** [comment]
Would love to see the ability to use tab(listener) without indicating the click.

+1 for merge this into the main branch

**Comment by tylerjroach** [comment]
^ Latest commits include a new listener that is used to pass the bottom navigation height as it animates in and out. Was used to animate another view (not FAB or Snackbar). If you want something like this without the other commits, I can create a separate pull request that only includes the listener changes.

**Comment by aurelhubert** [comment]
@tylerjroach I have merged manually your first two PR. I will close this one, can you create a new one for the y listener? Thanks!

**Pull request closed without merging**
